// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package genericimpl

import (
	"example/api/generic"
	"sync"
)

// NoGenericsRepositoryMock is a mock implementation of generic.NoGenericsRepository.
//
//	func TestSomethingThatUsesNoGenericsRepository(t *testing.T) {
//
//		// make and configure a mocked generic.NoGenericsRepository
//		mockedNoGenericsRepository := &NoGenericsRepositoryMock{
//			GetFunc: func(id string) (int, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedNoGenericsRepository in code that requires generic.NoGenericsRepository
//		// and then make assertions.
//
//	}
type NoGenericsRepositoryMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(id string) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// ID is the id argument value.
			ID string
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *NoGenericsRepositoryMock) Get(id string) (int, error) {
	if mock.GetFunc == nil {
		panic("NoGenericsRepositoryMock.GetFunc: method is nil but NoGenericsRepository.Get was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedNoGenericsRepository.GetCalls())
func (mock *NoGenericsRepositoryMock) GetCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// RepositoryMock is a mock implementation of generic.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked generic.Repository
//		mockedRepository := &RepositoryMock{
//			GetFunc: func(id string) (generic.Entity[T], error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedRepository in code that requires generic.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock[T any] struct {
	// GetFunc mocks the Get method.
	GetFunc func(id string) (generic.Entity[T], error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// ID is the id argument value.
			ID string
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *RepositoryMock[T]) Get(id string) (generic.Entity[T], error) {
	if mock.GetFunc == nil {
		panic("RepositoryMock.GetFunc: method is nil but Repository.Get was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedRepository.GetCalls())
func (mock *RepositoryMock[T]) GetCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
