// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package nestedimpl

import (
	"sync"
)

// RepositoryMock is a mock implementation of nested.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked nested.Repository
//		mockedRepository := &RepositoryMock{
//			HelloWorldFunc: func() string {
//				panic("mock out the HelloWorld method")
//			},
//		}
//
//		// use mockedRepository in code that requires nested.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// HelloWorldFunc mocks the HelloWorld method.
	HelloWorldFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// HelloWorld holds details about calls to the HelloWorld method.
		HelloWorld []struct {
		}
	}
	lockHelloWorld sync.RWMutex
}

// HelloWorld calls HelloWorldFunc.
func (mock *RepositoryMock) HelloWorld() string {
	if mock.HelloWorldFunc == nil {
		panic("RepositoryMock.HelloWorldFunc: method is nil but Repository.HelloWorld was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHelloWorld.Lock()
	mock.calls.HelloWorld = append(mock.calls.HelloWorld, callInfo)
	mock.lockHelloWorld.Unlock()
	return mock.HelloWorldFunc()
}

// HelloWorldCalls gets all the calls that were made to HelloWorld.
// Check the length with:
//
//	len(mockedRepository.HelloWorldCalls())
func (mock *RepositoryMock) HelloWorldCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHelloWorld.RLock()
	calls = mock.calls.HelloWorld
	mock.lockHelloWorld.RUnlock()
	return calls
}
