// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package heisenbergimpl

import (
	"context"
	"sync"
)

// NotificationServiceMock is a mock implementation of heisenberg.NotificationService.
//
//	func TestSomethingThatUsesNotificationService(t *testing.T) {
//
//		// make and configure a mocked heisenberg.NotificationService
//		mockedNotificationService := &NotificationServiceMock{
//			GetStatusFunc: func(ctx context.Context, id string) (string, error) {
//				panic("mock out the GetStatus method")
//			},
//			SendAlertFunc: func(ctx context.Context, message string) error {
//				panic("mock out the SendAlert method")
//			},
//		}
//
//		// use mockedNotificationService in code that requires heisenberg.NotificationService
//		// and then make assertions.
//
//	}
type NotificationServiceMock struct {
	// GetStatusFunc mocks the GetStatus method.
	GetStatusFunc func(ctx context.Context, id string) (string, error)

	// SendAlertFunc mocks the SendAlert method.
	SendAlertFunc func(ctx context.Context, message string) error

	// calls tracks calls to the methods.
	calls struct {
		// GetStatus holds details about calls to the GetStatus method.
		GetStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// SendAlert holds details about calls to the SendAlert method.
		SendAlert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Message is the message argument value.
			Message string
		}
	}
	lockGetStatus sync.RWMutex
	lockSendAlert sync.RWMutex
}

// GetStatus calls GetStatusFunc.
func (mock *NotificationServiceMock) GetStatus(ctx context.Context, id string) (string, error) {
	if mock.GetStatusFunc == nil {
		panic("NotificationServiceMock.GetStatusFunc: method is nil but NotificationService.GetStatus was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetStatus.Lock()
	mock.calls.GetStatus = append(mock.calls.GetStatus, callInfo)
	mock.lockGetStatus.Unlock()
	return mock.GetStatusFunc(ctx, id)
}

// GetStatusCalls gets all the calls that were made to GetStatus.
// Check the length with:
//
//	len(mockedNotificationService.GetStatusCalls())
func (mock *NotificationServiceMock) GetStatusCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetStatus.RLock()
	calls = mock.calls.GetStatus
	mock.lockGetStatus.RUnlock()
	return calls
}

// SendAlert calls SendAlertFunc.
func (mock *NotificationServiceMock) SendAlert(ctx context.Context, message string) error {
	if mock.SendAlertFunc == nil {
		panic("NotificationServiceMock.SendAlertFunc: method is nil but NotificationService.SendAlert was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Message string
	}{
		Ctx:     ctx,
		Message: message,
	}
	mock.lockSendAlert.Lock()
	mock.calls.SendAlert = append(mock.calls.SendAlert, callInfo)
	mock.lockSendAlert.Unlock()
	return mock.SendAlertFunc(ctx, message)
}

// SendAlertCalls gets all the calls that were made to SendAlert.
// Check the length with:
//
//	len(mockedNotificationService.SendAlertCalls())
func (mock *NotificationServiceMock) SendAlertCalls() []struct {
	Ctx     context.Context
	Message string
} {
	var calls []struct {
		Ctx     context.Context
		Message string
	}
	mock.lockSendAlert.RLock()
	calls = mock.calls.SendAlert
	mock.lockSendAlert.RUnlock()
	return calls
}
