// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package heisenbergimpl

import (
	"context"
	"example/api/heisenberg"
	"sync"
)

// ChemistryRepositoryMock is a mock implementation of heisenberg.ChemistryRepository.
//
//	func TestSomethingThatUsesChemistryRepository(t *testing.T) {
//
//		// make and configure a mocked heisenberg.ChemistryRepository
//		mockedChemistryRepository := &ChemistryRepositoryMock{
//			CookFunc: func(ctx context.Context, formula heisenberg.Formula) (*heisenberg.Batch, error) {
//				panic("mock out the Cook method")
//			},
//			GetBatchFunc: func(ctx context.Context, id string) (*heisenberg.Batch, error) {
//				panic("mock out the GetBatch method")
//			},
//			OptimizeFormulaFunc: func(formula heisenberg.Formula) (heisenberg.Formula, []string, error) {
//				panic("mock out the OptimizeFormula method")
//			},
//			TestMethodFunc: func(ctx context.Context, input string) (string, error) {
//				panic("mock out the TestMethod method")
//			},
//		}
//
//		// use mockedChemistryRepository in code that requires heisenberg.ChemistryRepository
//		// and then make assertions.
//
//	}
type ChemistryRepositoryMock struct {
	// CookFunc mocks the Cook method.
	CookFunc func(ctx context.Context, formula heisenberg.Formula) (*heisenberg.Batch, error)

	// GetBatchFunc mocks the GetBatch method.
	GetBatchFunc func(ctx context.Context, id string) (*heisenberg.Batch, error)

	// OptimizeFormulaFunc mocks the OptimizeFormula method.
	OptimizeFormulaFunc func(formula heisenberg.Formula) (heisenberg.Formula, []string, error)

	// TestMethodFunc mocks the TestMethod method.
	TestMethodFunc func(ctx context.Context, input string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Cook holds details about calls to the Cook method.
		Cook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Formula is the formula argument value.
			Formula heisenberg.Formula
		}
		// GetBatch holds details about calls to the GetBatch method.
		GetBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// OptimizeFormula holds details about calls to the OptimizeFormula method.
		OptimizeFormula []struct {
			// Formula is the formula argument value.
			Formula heisenberg.Formula
		}
		// TestMethod holds details about calls to the TestMethod method.
		TestMethod []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input string
		}
	}
	lockCook            sync.RWMutex
	lockGetBatch        sync.RWMutex
	lockOptimizeFormula sync.RWMutex
	lockTestMethod      sync.RWMutex
}

// Cook calls CookFunc.
func (mock *ChemistryRepositoryMock) Cook(ctx context.Context, formula heisenberg.Formula) (*heisenberg.Batch, error) {
	if mock.CookFunc == nil {
		panic("ChemistryRepositoryMock.CookFunc: method is nil but ChemistryRepository.Cook was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Formula heisenberg.Formula
	}{
		Ctx:     ctx,
		Formula: formula,
	}
	mock.lockCook.Lock()
	mock.calls.Cook = append(mock.calls.Cook, callInfo)
	mock.lockCook.Unlock()
	return mock.CookFunc(ctx, formula)
}

// CookCalls gets all the calls that were made to Cook.
// Check the length with:
//
//	len(mockedChemistryRepository.CookCalls())
func (mock *ChemistryRepositoryMock) CookCalls() []struct {
	Ctx     context.Context
	Formula heisenberg.Formula
} {
	var calls []struct {
		Ctx     context.Context
		Formula heisenberg.Formula
	}
	mock.lockCook.RLock()
	calls = mock.calls.Cook
	mock.lockCook.RUnlock()
	return calls
}

// GetBatch calls GetBatchFunc.
func (mock *ChemistryRepositoryMock) GetBatch(ctx context.Context, id string) (*heisenberg.Batch, error) {
	if mock.GetBatchFunc == nil {
		panic("ChemistryRepositoryMock.GetBatchFunc: method is nil but ChemistryRepository.GetBatch was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetBatch.Lock()
	mock.calls.GetBatch = append(mock.calls.GetBatch, callInfo)
	mock.lockGetBatch.Unlock()
	return mock.GetBatchFunc(ctx, id)
}

// GetBatchCalls gets all the calls that were made to GetBatch.
// Check the length with:
//
//	len(mockedChemistryRepository.GetBatchCalls())
func (mock *ChemistryRepositoryMock) GetBatchCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetBatch.RLock()
	calls = mock.calls.GetBatch
	mock.lockGetBatch.RUnlock()
	return calls
}

// OptimizeFormula calls OptimizeFormulaFunc.
func (mock *ChemistryRepositoryMock) OptimizeFormula(formula heisenberg.Formula) (heisenberg.Formula, []string, error) {
	if mock.OptimizeFormulaFunc == nil {
		panic("ChemistryRepositoryMock.OptimizeFormulaFunc: method is nil but ChemistryRepository.OptimizeFormula was just called")
	}
	callInfo := struct {
		Formula heisenberg.Formula
	}{
		Formula: formula,
	}
	mock.lockOptimizeFormula.Lock()
	mock.calls.OptimizeFormula = append(mock.calls.OptimizeFormula, callInfo)
	mock.lockOptimizeFormula.Unlock()
	return mock.OptimizeFormulaFunc(formula)
}

// OptimizeFormulaCalls gets all the calls that were made to OptimizeFormula.
// Check the length with:
//
//	len(mockedChemistryRepository.OptimizeFormulaCalls())
func (mock *ChemistryRepositoryMock) OptimizeFormulaCalls() []struct {
	Formula heisenberg.Formula
} {
	var calls []struct {
		Formula heisenberg.Formula
	}
	mock.lockOptimizeFormula.RLock()
	calls = mock.calls.OptimizeFormula
	mock.lockOptimizeFormula.RUnlock()
	return calls
}

// TestMethod calls TestMethodFunc.
func (mock *ChemistryRepositoryMock) TestMethod(ctx context.Context, input string) (string, error) {
	if mock.TestMethodFunc == nil {
		panic("ChemistryRepositoryMock.TestMethodFunc: method is nil but ChemistryRepository.TestMethod was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input string
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockTestMethod.Lock()
	mock.calls.TestMethod = append(mock.calls.TestMethod, callInfo)
	mock.lockTestMethod.Unlock()
	return mock.TestMethodFunc(ctx, input)
}

// TestMethodCalls gets all the calls that were made to TestMethod.
// Check the length with:
//
//	len(mockedChemistryRepository.TestMethodCalls())
func (mock *ChemistryRepositoryMock) TestMethodCalls() []struct {
	Ctx   context.Context
	Input string
} {
	var calls []struct {
		Ctx   context.Context
		Input string
	}
	mock.lockTestMethod.RLock()
	calls = mock.calls.TestMethod
	mock.lockTestMethod.RUnlock()
	return calls
}

// MoneyRepositoryMock is a mock implementation of heisenberg.MoneyRepository.
//
//	func TestSomethingThatUsesMoneyRepository(t *testing.T) {
//
//		// make and configure a mocked heisenberg.MoneyRepository
//		mockedMoneyRepository := &MoneyRepositoryMock{
//			LaunderFunc: func(ctx context.Context, amount *float64) (*float64, error) {
//				panic("mock out the Launder method")
//			},
//			ProcessPaymentsFunc: func(ctx context.Context, amounts []float64) ([]string, error) {
//				panic("mock out the ProcessPayments method")
//			},
//		}
//
//		// use mockedMoneyRepository in code that requires heisenberg.MoneyRepository
//		// and then make assertions.
//
//	}
type MoneyRepositoryMock struct {
	// LaunderFunc mocks the Launder method.
	LaunderFunc func(ctx context.Context, amount *float64) (*float64, error)

	// ProcessPaymentsFunc mocks the ProcessPayments method.
	ProcessPaymentsFunc func(ctx context.Context, amounts []float64) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Launder holds details about calls to the Launder method.
		Launder []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Amount is the amount argument value.
			Amount *float64
		}
		// ProcessPayments holds details about calls to the ProcessPayments method.
		ProcessPayments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Amounts is the amounts argument value.
			Amounts []float64
		}
	}
	lockLaunder         sync.RWMutex
	lockProcessPayments sync.RWMutex
}

// Launder calls LaunderFunc.
func (mock *MoneyRepositoryMock) Launder(ctx context.Context, amount *float64) (*float64, error) {
	if mock.LaunderFunc == nil {
		panic("MoneyRepositoryMock.LaunderFunc: method is nil but MoneyRepository.Launder was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Amount *float64
	}{
		Ctx:    ctx,
		Amount: amount,
	}
	mock.lockLaunder.Lock()
	mock.calls.Launder = append(mock.calls.Launder, callInfo)
	mock.lockLaunder.Unlock()
	return mock.LaunderFunc(ctx, amount)
}

// LaunderCalls gets all the calls that were made to Launder.
// Check the length with:
//
//	len(mockedMoneyRepository.LaunderCalls())
func (mock *MoneyRepositoryMock) LaunderCalls() []struct {
	Ctx    context.Context
	Amount *float64
} {
	var calls []struct {
		Ctx    context.Context
		Amount *float64
	}
	mock.lockLaunder.RLock()
	calls = mock.calls.Launder
	mock.lockLaunder.RUnlock()
	return calls
}

// ProcessPayments calls ProcessPaymentsFunc.
func (mock *MoneyRepositoryMock) ProcessPayments(ctx context.Context, amounts []float64) ([]string, error) {
	if mock.ProcessPaymentsFunc == nil {
		panic("MoneyRepositoryMock.ProcessPaymentsFunc: method is nil but MoneyRepository.ProcessPayments was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Amounts []float64
	}{
		Ctx:     ctx,
		Amounts: amounts,
	}
	mock.lockProcessPayments.Lock()
	mock.calls.ProcessPayments = append(mock.calls.ProcessPayments, callInfo)
	mock.lockProcessPayments.Unlock()
	return mock.ProcessPaymentsFunc(ctx, amounts)
}

// ProcessPaymentsCalls gets all the calls that were made to ProcessPayments.
// Check the length with:
//
//	len(mockedMoneyRepository.ProcessPaymentsCalls())
func (mock *MoneyRepositoryMock) ProcessPaymentsCalls() []struct {
	Ctx     context.Context
	Amounts []float64
} {
	var calls []struct {
		Ctx     context.Context
		Amounts []float64
	}
	mock.lockProcessPayments.RLock()
	calls = mock.calls.ProcessPayments
	mock.lockProcessPayments.RUnlock()
	return calls
}
