// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package spongebobimpl

import (
	"context"
	"sync"
)

// FryServiceMock is a mock implementation of spongebob.FryService.
//
//	func TestSomethingThatUsesFryService(t *testing.T) {
//
//		// make and configure a mocked spongebob.FryService
//		mockedFryService := &FryServiceMock{
//			CookFriesFunc: func(ctx context.Context, size string) (string, error) {
//				panic("mock out the CookFries method")
//			},
//			SeasonFriesFunc: func(ctx context.Context, batchID string, seasoning string) error {
//				panic("mock out the SeasonFries method")
//			},
//		}
//
//		// use mockedFryService in code that requires spongebob.FryService
//		// and then make assertions.
//
//	}
type FryServiceMock struct {
	// CookFriesFunc mocks the CookFries method.
	CookFriesFunc func(ctx context.Context, size string) (string, error)

	// SeasonFriesFunc mocks the SeasonFries method.
	SeasonFriesFunc func(ctx context.Context, batchID string, seasoning string) error

	// calls tracks calls to the methods.
	calls struct {
		// CookFries holds details about calls to the CookFries method.
		CookFries []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Size is the size argument value.
			Size string
		}
		// SeasonFries holds details about calls to the SeasonFries method.
		SeasonFries []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BatchID is the batchID argument value.
			BatchID string
			// Seasoning is the seasoning argument value.
			Seasoning string
		}
	}
	lockCookFries   sync.RWMutex
	lockSeasonFries sync.RWMutex
}

// CookFries calls CookFriesFunc.
func (mock *FryServiceMock) CookFries(ctx context.Context, size string) (string, error) {
	if mock.CookFriesFunc == nil {
		panic("FryServiceMock.CookFriesFunc: method is nil but FryService.CookFries was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Size string
	}{
		Ctx:  ctx,
		Size: size,
	}
	mock.lockCookFries.Lock()
	mock.calls.CookFries = append(mock.calls.CookFries, callInfo)
	mock.lockCookFries.Unlock()
	return mock.CookFriesFunc(ctx, size)
}

// CookFriesCalls gets all the calls that were made to CookFries.
// Check the length with:
//
//	len(mockedFryService.CookFriesCalls())
func (mock *FryServiceMock) CookFriesCalls() []struct {
	Ctx  context.Context
	Size string
} {
	var calls []struct {
		Ctx  context.Context
		Size string
	}
	mock.lockCookFries.RLock()
	calls = mock.calls.CookFries
	mock.lockCookFries.RUnlock()
	return calls
}

// SeasonFries calls SeasonFriesFunc.
func (mock *FryServiceMock) SeasonFries(ctx context.Context, batchID string, seasoning string) error {
	if mock.SeasonFriesFunc == nil {
		panic("FryServiceMock.SeasonFriesFunc: method is nil but FryService.SeasonFries was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		BatchID   string
		Seasoning string
	}{
		Ctx:       ctx,
		BatchID:   batchID,
		Seasoning: seasoning,
	}
	mock.lockSeasonFries.Lock()
	mock.calls.SeasonFries = append(mock.calls.SeasonFries, callInfo)
	mock.lockSeasonFries.Unlock()
	return mock.SeasonFriesFunc(ctx, batchID, seasoning)
}

// SeasonFriesCalls gets all the calls that were made to SeasonFries.
// Check the length with:
//
//	len(mockedFryService.SeasonFriesCalls())
func (mock *FryServiceMock) SeasonFriesCalls() []struct {
	Ctx       context.Context
	BatchID   string
	Seasoning string
} {
	var calls []struct {
		Ctx       context.Context
		BatchID   string
		Seasoning string
	}
	mock.lockSeasonFries.RLock()
	calls = mock.calls.SeasonFries
	mock.lockSeasonFries.RUnlock()
	return calls
}

// PattyServiceMock is a mock implementation of spongebob.PattyService.
//
//	func TestSomethingThatUsesPattyService(t *testing.T) {
//
//		// make and configure a mocked spongebob.PattyService
//		mockedPattyService := &PattyServiceMock{
//			GrillPattyFunc: func(ctx context.Context, orderID string) error {
//				panic("mock out the GrillPatty method")
//			},
//			IsPattyReadyFunc: func(ctx context.Context, orderID string) (bool, error) {
//				panic("mock out the IsPattyReady method")
//			},
//			ServePattyFunc: func(ctx context.Context, orderID string, customerName string) error {
//				panic("mock out the ServePatty method")
//			},
//		}
//
//		// use mockedPattyService in code that requires spongebob.PattyService
//		// and then make assertions.
//
//	}
type PattyServiceMock struct {
	// GrillPattyFunc mocks the GrillPatty method.
	GrillPattyFunc func(ctx context.Context, orderID string) error

	// IsPattyReadyFunc mocks the IsPattyReady method.
	IsPattyReadyFunc func(ctx context.Context, orderID string) (bool, error)

	// ServePattyFunc mocks the ServePatty method.
	ServePattyFunc func(ctx context.Context, orderID string, customerName string) error

	// calls tracks calls to the methods.
	calls struct {
		// GrillPatty holds details about calls to the GrillPatty method.
		GrillPatty []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrderID is the orderID argument value.
			OrderID string
		}
		// IsPattyReady holds details about calls to the IsPattyReady method.
		IsPattyReady []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrderID is the orderID argument value.
			OrderID string
		}
		// ServePatty holds details about calls to the ServePatty method.
		ServePatty []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrderID is the orderID argument value.
			OrderID string
			// CustomerName is the customerName argument value.
			CustomerName string
		}
	}
	lockGrillPatty   sync.RWMutex
	lockIsPattyReady sync.RWMutex
	lockServePatty   sync.RWMutex
}

// GrillPatty calls GrillPattyFunc.
func (mock *PattyServiceMock) GrillPatty(ctx context.Context, orderID string) error {
	if mock.GrillPattyFunc == nil {
		panic("PattyServiceMock.GrillPattyFunc: method is nil but PattyService.GrillPatty was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrderID string
	}{
		Ctx:     ctx,
		OrderID: orderID,
	}
	mock.lockGrillPatty.Lock()
	mock.calls.GrillPatty = append(mock.calls.GrillPatty, callInfo)
	mock.lockGrillPatty.Unlock()
	return mock.GrillPattyFunc(ctx, orderID)
}

// GrillPattyCalls gets all the calls that were made to GrillPatty.
// Check the length with:
//
//	len(mockedPattyService.GrillPattyCalls())
func (mock *PattyServiceMock) GrillPattyCalls() []struct {
	Ctx     context.Context
	OrderID string
} {
	var calls []struct {
		Ctx     context.Context
		OrderID string
	}
	mock.lockGrillPatty.RLock()
	calls = mock.calls.GrillPatty
	mock.lockGrillPatty.RUnlock()
	return calls
}

// IsPattyReady calls IsPattyReadyFunc.
func (mock *PattyServiceMock) IsPattyReady(ctx context.Context, orderID string) (bool, error) {
	if mock.IsPattyReadyFunc == nil {
		panic("PattyServiceMock.IsPattyReadyFunc: method is nil but PattyService.IsPattyReady was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrderID string
	}{
		Ctx:     ctx,
		OrderID: orderID,
	}
	mock.lockIsPattyReady.Lock()
	mock.calls.IsPattyReady = append(mock.calls.IsPattyReady, callInfo)
	mock.lockIsPattyReady.Unlock()
	return mock.IsPattyReadyFunc(ctx, orderID)
}

// IsPattyReadyCalls gets all the calls that were made to IsPattyReady.
// Check the length with:
//
//	len(mockedPattyService.IsPattyReadyCalls())
func (mock *PattyServiceMock) IsPattyReadyCalls() []struct {
	Ctx     context.Context
	OrderID string
} {
	var calls []struct {
		Ctx     context.Context
		OrderID string
	}
	mock.lockIsPattyReady.RLock()
	calls = mock.calls.IsPattyReady
	mock.lockIsPattyReady.RUnlock()
	return calls
}

// ServePatty calls ServePattyFunc.
func (mock *PattyServiceMock) ServePatty(ctx context.Context, orderID string, customerName string) error {
	if mock.ServePattyFunc == nil {
		panic("PattyServiceMock.ServePattyFunc: method is nil but PattyService.ServePatty was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		OrderID      string
		CustomerName string
	}{
		Ctx:          ctx,
		OrderID:      orderID,
		CustomerName: customerName,
	}
	mock.lockServePatty.Lock()
	mock.calls.ServePatty = append(mock.calls.ServePatty, callInfo)
	mock.lockServePatty.Unlock()
	return mock.ServePattyFunc(ctx, orderID, customerName)
}

// ServePattyCalls gets all the calls that were made to ServePatty.
// Check the length with:
//
//	len(mockedPattyService.ServePattyCalls())
func (mock *PattyServiceMock) ServePattyCalls() []struct {
	Ctx          context.Context
	OrderID      string
	CustomerName string
} {
	var calls []struct {
		Ctx          context.Context
		OrderID      string
		CustomerName string
	}
	mock.lockServePatty.RLock()
	calls = mock.calls.ServePatty
	mock.lockServePatty.RUnlock()
	return calls
}
