// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package spongebobimpl

import (
	"context"
	"example/api/spongebob"
	"sync"
)

// JellyfishingRepositoryMock is a mock implementation of spongebob.JellyfishingRepository.
//
//	func TestSomethingThatUsesJellyfishingRepository(t *testing.T) {
//
//		// make and configure a mocked spongebob.JellyfishingRepository
//		mockedJellyfishingRepository := &JellyfishingRepositoryMock{
//			CatchJellyfishFunc: func(ctx context.Context, jellyfish spongebob.Jellyfish) error {
//				panic("mock out the CatchJellyfish method")
//			},
//			CountJellyfishFunc: func(ctx context.Context, area string) (int, error) {
//				panic("mock out the CountJellyfish method")
//			},
//			GetBestSpotFunc: func(ctx context.Context) (string, error) {
//				panic("mock out the GetBestSpot method")
//			},
//			ReleaseJellyfishFunc: func(ctx context.Context, jellyfish []spongebob.Jellyfish) error {
//				panic("mock out the ReleaseJellyfish method")
//			},
//		}
//
//		// use mockedJellyfishingRepository in code that requires spongebob.JellyfishingRepository
//		// and then make assertions.
//
//	}
type JellyfishingRepositoryMock struct {
	// CatchJellyfishFunc mocks the CatchJellyfish method.
	CatchJellyfishFunc func(ctx context.Context, jellyfish spongebob.Jellyfish) error

	// CountJellyfishFunc mocks the CountJellyfish method.
	CountJellyfishFunc func(ctx context.Context, area string) (int, error)

	// GetBestSpotFunc mocks the GetBestSpot method.
	GetBestSpotFunc func(ctx context.Context) (string, error)

	// ReleaseJellyfishFunc mocks the ReleaseJellyfish method.
	ReleaseJellyfishFunc func(ctx context.Context, jellyfish []spongebob.Jellyfish) error

	// calls tracks calls to the methods.
	calls struct {
		// CatchJellyfish holds details about calls to the CatchJellyfish method.
		CatchJellyfish []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Jellyfish is the jellyfish argument value.
			Jellyfish spongebob.Jellyfish
		}
		// CountJellyfish holds details about calls to the CountJellyfish method.
		CountJellyfish []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Area is the area argument value.
			Area string
		}
		// GetBestSpot holds details about calls to the GetBestSpot method.
		GetBestSpot []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ReleaseJellyfish holds details about calls to the ReleaseJellyfish method.
		ReleaseJellyfish []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Jellyfish is the jellyfish argument value.
			Jellyfish []spongebob.Jellyfish
		}
	}
	lockCatchJellyfish   sync.RWMutex
	lockCountJellyfish   sync.RWMutex
	lockGetBestSpot      sync.RWMutex
	lockReleaseJellyfish sync.RWMutex
}

// CatchJellyfish calls CatchJellyfishFunc.
func (mock *JellyfishingRepositoryMock) CatchJellyfish(ctx context.Context, jellyfish spongebob.Jellyfish) error {
	if mock.CatchJellyfishFunc == nil {
		panic("JellyfishingRepositoryMock.CatchJellyfishFunc: method is nil but JellyfishingRepository.CatchJellyfish was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Jellyfish spongebob.Jellyfish
	}{
		Ctx:       ctx,
		Jellyfish: jellyfish,
	}
	mock.lockCatchJellyfish.Lock()
	mock.calls.CatchJellyfish = append(mock.calls.CatchJellyfish, callInfo)
	mock.lockCatchJellyfish.Unlock()
	return mock.CatchJellyfishFunc(ctx, jellyfish)
}

// CatchJellyfishCalls gets all the calls that were made to CatchJellyfish.
// Check the length with:
//
//	len(mockedJellyfishingRepository.CatchJellyfishCalls())
func (mock *JellyfishingRepositoryMock) CatchJellyfishCalls() []struct {
	Ctx       context.Context
	Jellyfish spongebob.Jellyfish
} {
	var calls []struct {
		Ctx       context.Context
		Jellyfish spongebob.Jellyfish
	}
	mock.lockCatchJellyfish.RLock()
	calls = mock.calls.CatchJellyfish
	mock.lockCatchJellyfish.RUnlock()
	return calls
}

// CountJellyfish calls CountJellyfishFunc.
func (mock *JellyfishingRepositoryMock) CountJellyfish(ctx context.Context, area string) (int, error) {
	if mock.CountJellyfishFunc == nil {
		panic("JellyfishingRepositoryMock.CountJellyfishFunc: method is nil but JellyfishingRepository.CountJellyfish was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Area string
	}{
		Ctx:  ctx,
		Area: area,
	}
	mock.lockCountJellyfish.Lock()
	mock.calls.CountJellyfish = append(mock.calls.CountJellyfish, callInfo)
	mock.lockCountJellyfish.Unlock()
	return mock.CountJellyfishFunc(ctx, area)
}

// CountJellyfishCalls gets all the calls that were made to CountJellyfish.
// Check the length with:
//
//	len(mockedJellyfishingRepository.CountJellyfishCalls())
func (mock *JellyfishingRepositoryMock) CountJellyfishCalls() []struct {
	Ctx  context.Context
	Area string
} {
	var calls []struct {
		Ctx  context.Context
		Area string
	}
	mock.lockCountJellyfish.RLock()
	calls = mock.calls.CountJellyfish
	mock.lockCountJellyfish.RUnlock()
	return calls
}

// GetBestSpot calls GetBestSpotFunc.
func (mock *JellyfishingRepositoryMock) GetBestSpot(ctx context.Context) (string, error) {
	if mock.GetBestSpotFunc == nil {
		panic("JellyfishingRepositoryMock.GetBestSpotFunc: method is nil but JellyfishingRepository.GetBestSpot was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetBestSpot.Lock()
	mock.calls.GetBestSpot = append(mock.calls.GetBestSpot, callInfo)
	mock.lockGetBestSpot.Unlock()
	return mock.GetBestSpotFunc(ctx)
}

// GetBestSpotCalls gets all the calls that were made to GetBestSpot.
// Check the length with:
//
//	len(mockedJellyfishingRepository.GetBestSpotCalls())
func (mock *JellyfishingRepositoryMock) GetBestSpotCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetBestSpot.RLock()
	calls = mock.calls.GetBestSpot
	mock.lockGetBestSpot.RUnlock()
	return calls
}

// ReleaseJellyfish calls ReleaseJellyfishFunc.
func (mock *JellyfishingRepositoryMock) ReleaseJellyfish(ctx context.Context, jellyfish []spongebob.Jellyfish) error {
	if mock.ReleaseJellyfishFunc == nil {
		panic("JellyfishingRepositoryMock.ReleaseJellyfishFunc: method is nil but JellyfishingRepository.ReleaseJellyfish was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Jellyfish []spongebob.Jellyfish
	}{
		Ctx:       ctx,
		Jellyfish: jellyfish,
	}
	mock.lockReleaseJellyfish.Lock()
	mock.calls.ReleaseJellyfish = append(mock.calls.ReleaseJellyfish, callInfo)
	mock.lockReleaseJellyfish.Unlock()
	return mock.ReleaseJellyfishFunc(ctx, jellyfish)
}

// ReleaseJellyfishCalls gets all the calls that were made to ReleaseJellyfish.
// Check the length with:
//
//	len(mockedJellyfishingRepository.ReleaseJellyfishCalls())
func (mock *JellyfishingRepositoryMock) ReleaseJellyfishCalls() []struct {
	Ctx       context.Context
	Jellyfish []spongebob.Jellyfish
} {
	var calls []struct {
		Ctx       context.Context
		Jellyfish []spongebob.Jellyfish
	}
	mock.lockReleaseJellyfish.RLock()
	calls = mock.calls.ReleaseJellyfish
	mock.lockReleaseJellyfish.RUnlock()
	return calls
}

// KrustyKrabRepositoryMock is a mock implementation of spongebob.KrustyKrabRepository.
//
//	func TestSomethingThatUsesKrustyKrabRepository(t *testing.T) {
//
//		// make and configure a mocked spongebob.KrustyKrabRepository
//		mockedKrustyKrabRepository := &KrustyKrabRepositoryMock{
//			CookPattyFunc: func(ctx context.Context, toppings []string) (*spongebob.KrabbyPatty, error) {
//				panic("mock out the CookPatty method")
//			},
//			GetMenuFunc: func(ctx context.Context) ([]spongebob.MenuItem, error) {
//				panic("mock out the GetMenu method")
//			},
//			ServeCustomerFunc: func(ctx context.Context, patty spongebob.KrabbyPatty, customerName string) error {
//				panic("mock out the ServeCustomer method")
//			},
//			UpdateMenuFunc: func(ctx context.Context, items []spongebob.MenuItem) error {
//				panic("mock out the UpdateMenu method")
//			},
//		}
//
//		// use mockedKrustyKrabRepository in code that requires spongebob.KrustyKrabRepository
//		// and then make assertions.
//
//	}
type KrustyKrabRepositoryMock struct {
	// CookPattyFunc mocks the CookPatty method.
	CookPattyFunc func(ctx context.Context, toppings []string) (*spongebob.KrabbyPatty, error)

	// GetMenuFunc mocks the GetMenu method.
	GetMenuFunc func(ctx context.Context) ([]spongebob.MenuItem, error)

	// ServeCustomerFunc mocks the ServeCustomer method.
	ServeCustomerFunc func(ctx context.Context, patty spongebob.KrabbyPatty, customerName string) error

	// UpdateMenuFunc mocks the UpdateMenu method.
	UpdateMenuFunc func(ctx context.Context, items []spongebob.MenuItem) error

	// calls tracks calls to the methods.
	calls struct {
		// CookPatty holds details about calls to the CookPatty method.
		CookPatty []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Toppings is the toppings argument value.
			Toppings []string
		}
		// GetMenu holds details about calls to the GetMenu method.
		GetMenu []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ServeCustomer holds details about calls to the ServeCustomer method.
		ServeCustomer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Patty is the patty argument value.
			Patty spongebob.KrabbyPatty
			// CustomerName is the customerName argument value.
			CustomerName string
		}
		// UpdateMenu holds details about calls to the UpdateMenu method.
		UpdateMenu []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Items is the items argument value.
			Items []spongebob.MenuItem
		}
	}
	lockCookPatty     sync.RWMutex
	lockGetMenu       sync.RWMutex
	lockServeCustomer sync.RWMutex
	lockUpdateMenu    sync.RWMutex
}

// CookPatty calls CookPattyFunc.
func (mock *KrustyKrabRepositoryMock) CookPatty(ctx context.Context, toppings []string) (*spongebob.KrabbyPatty, error) {
	if mock.CookPattyFunc == nil {
		panic("KrustyKrabRepositoryMock.CookPattyFunc: method is nil but KrustyKrabRepository.CookPatty was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Toppings []string
	}{
		Ctx:      ctx,
		Toppings: toppings,
	}
	mock.lockCookPatty.Lock()
	mock.calls.CookPatty = append(mock.calls.CookPatty, callInfo)
	mock.lockCookPatty.Unlock()
	return mock.CookPattyFunc(ctx, toppings)
}

// CookPattyCalls gets all the calls that were made to CookPatty.
// Check the length with:
//
//	len(mockedKrustyKrabRepository.CookPattyCalls())
func (mock *KrustyKrabRepositoryMock) CookPattyCalls() []struct {
	Ctx      context.Context
	Toppings []string
} {
	var calls []struct {
		Ctx      context.Context
		Toppings []string
	}
	mock.lockCookPatty.RLock()
	calls = mock.calls.CookPatty
	mock.lockCookPatty.RUnlock()
	return calls
}

// GetMenu calls GetMenuFunc.
func (mock *KrustyKrabRepositoryMock) GetMenu(ctx context.Context) ([]spongebob.MenuItem, error) {
	if mock.GetMenuFunc == nil {
		panic("KrustyKrabRepositoryMock.GetMenuFunc: method is nil but KrustyKrabRepository.GetMenu was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetMenu.Lock()
	mock.calls.GetMenu = append(mock.calls.GetMenu, callInfo)
	mock.lockGetMenu.Unlock()
	return mock.GetMenuFunc(ctx)
}

// GetMenuCalls gets all the calls that were made to GetMenu.
// Check the length with:
//
//	len(mockedKrustyKrabRepository.GetMenuCalls())
func (mock *KrustyKrabRepositoryMock) GetMenuCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetMenu.RLock()
	calls = mock.calls.GetMenu
	mock.lockGetMenu.RUnlock()
	return calls
}

// ServeCustomer calls ServeCustomerFunc.
func (mock *KrustyKrabRepositoryMock) ServeCustomer(ctx context.Context, patty spongebob.KrabbyPatty, customerName string) error {
	if mock.ServeCustomerFunc == nil {
		panic("KrustyKrabRepositoryMock.ServeCustomerFunc: method is nil but KrustyKrabRepository.ServeCustomer was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Patty        spongebob.KrabbyPatty
		CustomerName string
	}{
		Ctx:          ctx,
		Patty:        patty,
		CustomerName: customerName,
	}
	mock.lockServeCustomer.Lock()
	mock.calls.ServeCustomer = append(mock.calls.ServeCustomer, callInfo)
	mock.lockServeCustomer.Unlock()
	return mock.ServeCustomerFunc(ctx, patty, customerName)
}

// ServeCustomerCalls gets all the calls that were made to ServeCustomer.
// Check the length with:
//
//	len(mockedKrustyKrabRepository.ServeCustomerCalls())
func (mock *KrustyKrabRepositoryMock) ServeCustomerCalls() []struct {
	Ctx          context.Context
	Patty        spongebob.KrabbyPatty
	CustomerName string
} {
	var calls []struct {
		Ctx          context.Context
		Patty        spongebob.KrabbyPatty
		CustomerName string
	}
	mock.lockServeCustomer.RLock()
	calls = mock.calls.ServeCustomer
	mock.lockServeCustomer.RUnlock()
	return calls
}

// UpdateMenu calls UpdateMenuFunc.
func (mock *KrustyKrabRepositoryMock) UpdateMenu(ctx context.Context, items []spongebob.MenuItem) error {
	if mock.UpdateMenuFunc == nil {
		panic("KrustyKrabRepositoryMock.UpdateMenuFunc: method is nil but KrustyKrabRepository.UpdateMenu was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Items []spongebob.MenuItem
	}{
		Ctx:   ctx,
		Items: items,
	}
	mock.lockUpdateMenu.Lock()
	mock.calls.UpdateMenu = append(mock.calls.UpdateMenu, callInfo)
	mock.lockUpdateMenu.Unlock()
	return mock.UpdateMenuFunc(ctx, items)
}

// UpdateMenuCalls gets all the calls that were made to UpdateMenu.
// Check the length with:
//
//	len(mockedKrustyKrabRepository.UpdateMenuCalls())
func (mock *KrustyKrabRepositoryMock) UpdateMenuCalls() []struct {
	Ctx   context.Context
	Items []spongebob.MenuItem
} {
	var calls []struct {
		Ctx   context.Context
		Items []spongebob.MenuItem
	}
	mock.lockUpdateMenu.RLock()
	calls = mock.calls.UpdateMenu
	mock.lockUpdateMenu.RUnlock()
	return calls
}
